# SEO Values
title: Lincoln Lopes - GitHub Pages
tagline: The renowned dark theme for ...
description: Base de conhecimento sobre tecnologia, programação e desenvolvimento de software.
url: https://lincolnlopes.github.io
twitter: https://twitter.com/lincolngyn
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  public: true
  owner_name: Lincoln Lopes
  owner_url: https://github.com/lincolnlopes
  repository_url: https://github.com/lincolnlopes/lincolnlopes.github.io

mermaid: true
show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag