# Configurações básicas
title: Lincoln Lopes
description: Blog pessoal sobre desenvolvimento web, tecnologia e programação
baseurl: ""
url: "https://lincolnlopes.github.io"

# Autor
author:
  name: Lincoln Lopes
  bio: Desenvolvedor Full Stack & Entusiasta de Tecnologia
  location: Brasil
  avatar: /assets/images/avatar.jpg
  social:
    github: lincolnlopes
    linkedin: lincolnlopes
    twitter: lincolnlopes

# Configurações do Jekyll
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: /artigos/page:num/

# Coleções
collections:
  articles:
    output: true
    permalink: /artigos/:title/
  tutorials:
    output: true
    permalink: /tutoriais/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Excluir arquivos
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# Variáveis personalizadas
variables:
  primary_color: "#2563eb"
  success_color: "#22c55e"
  warning_color: "#f59e0b"
  danger_color: "#ef4444"
  border_color: "#e5e7eb"

# SEO
seo:
  title: Lincoln Lopes - Desenvolvimento e Tecnologia
  description: Blog pessoal sobre desenvolvimento, tecnologia e mais
  keywords: desenvolvimento, tecnologia, programação, devops, cloud
  author: Lincoln Lopes
  og_image: /assets/images/og-image.jpg
  twitter_card: summary_large_image

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# GitHub
github:
  username: lincolnlopes
  repository: lincolnlopes.github.io

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:slug/
  articles:
    output: true
    permalink: /articles/:slug/
  projects:
    output: true
    permalink: /projects/:slug/

# Collection defaults
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
      author: Lincoln Lopes
      comments: true
  - scope:
      path: ""
      type: articles
    values:
      layout: article
      author: Lincoln Lopes
      comments: true
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author: Lincoln Lopes
      comments: true

# Busca
search:
  enabled: true
  placeholder: "Buscar no site..."

# JavaScript
javascript:
  dependencies:
    - name: Font Awesome
      url: https://kit.fontawesome.com/your-kit-code.js
      async: true
    - name: Inter Font
      url: https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap
      async: true

# Comentários
comments:
  utterances:
    enabled: true
    repository: lincolnlopes/lincolnlopes.github.io
    issue_term: pathname
    label: 💬 Comentários
    theme: github-dark

# Build
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

sass:
  style: compressed