# SEO Values
title: Lincoln Lopes - GitHub Pages
tagline: The renowned dark theme for ...
description: Base de conhecimento sobre tecnologia, programação e desenvolvimento de software.
url: https://lincolnlopes.github.io
twitter: https://twitter.com/lincolngyn
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  public: true
  owner_name: Lincoln Lopes
  owner_url: https://github.com/lincolnlopes
  repository_url: https://github.com/lincolnlopes/lincolnlopes.github.io

mermaid: true
show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
  - faraday-retry

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/
  articles:
    output: true
    permalink: /articles/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Collection Defaults
defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
      author: "Lincoln Lopes"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
      author: "Lincoln Lopes"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Lincoln Lopes"

# Search Configuration
search_enabled: true
search_placeholder: "Buscar em tutoriais e artigos..."
search_min_chars: 2

# JavaScript Dependencies
javascript:
  - /assets/js/lunr.min.js
  - /assets/js/search.js